version: '3.9'

services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: dpiofguSAClknv

  java:
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      DB_USERNAME: postgres
      DB_HOST: db