name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print working directory
        run: pwd
      - name: List files
        run: ls -al
      - name: Print working directory
        run: cd ..
      - name: List files
        run: ls -al
      - uses: appleboy/ssh-action@v0.1.10
        with:
          host: 188.225.58.99
          username: root
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            chmod +x mvnw
            ./mvnw install
            ./mvnw spring-boot:run