name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: appleboy/ssh-action@v0.1.10
        with:
          host: 188.225.58.99
          username: root
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            rm --recursive itotdel-money
            git clone https://github.com/Stremilov/itotdel-money.git
            cd itotdel-money
            pwd
            ls -al
            ./mvnw install
            ./mvnw spring-boot:run